'use strict';

const Actions = {
  bang: `bang`,
  beer: `beer`,
  brawl: `brawl`,
  catbalou: `catbalou`,
  dodge: `dodge`,
  duel: `duel`,
  gatling: `gatling`,
  generalstore: `generalstore`,
  indians: `indians`,
  missed: `missed`,
  panic: `panic`,
  punch: `punch`,
  ragtime: `ragtime`,
  saloon: `saloon`,
  springfield: `springfield`,
  stagecoach: `stagecoach`,
  tequila: `tequila`,
  wellsfargo: `wellsfargo`,
  whisky: `whisky`,
};

const Items = {
  barrel: `barrel`,
  binocular: `binocular`,
  dynamite: `dynamite`,
  hideout: `hideout`,
  jail: `jail`,
  mustang: `mustang`,
  remington: `remington`,
  revcarbine: `revcarbine`,
  schofield: `schofield`,
  scope: `scope`,
  volcanic: `volcanic`,
  winchester: `winchester`,
};

const GunDistances = {
  [Items.volcanic]: 1,
  [Items.schofield]: 2,
  [Items.remington]: 3,
  [Items.revcarbine]: 4,
  [Items.winchester]: 5,
};

const QueueableActions = {
  bible: `bible`,
  buffalorifle: `buffalorifle`,
  cancan: `cancan`,
  canteen: `canteen`,
  conestoga: `conestoga`,
  derringer: `derringer`,
  howitzer: `howitzer`,
  ironplate: `ironplate`,
  knife: `knife`,
  pepperbox: `pepperbox`,
  ponyexpress: `ponyexpress`,
  sombrero: `sombrero`,
  tengallonhat: `tengallonhat`,
};

const Roles = {
  deputy: `deputy`,
  outlaw: `outlaw`,
  renegade: `renegade`,
  sheriff: `sheriff`,
  unknown: `unknown`,
};

const Skills = {
  apache: `apache`,
  bart: `bart`,
  belle: `belle`,
  chuck: `chuck`,
  claus: `claus`,
  duke: `duke`,
  elena: `elena`,
  greg: `greg`,
  gringo: `gringo`,
  herb: `herb`,
  holyday: `holyday`,
  jack: `jack`,
  janet: `janet`,
  jesse: `jesse`,
  joe: `joe`,
  johnny: `johnny`,
  jose: `jose`,
  jourdonnais: `jourdonnais`,
  kit: `kit`,
  molly: `molly`,
  noface: `noface`,
  pat: `pat`,
  paul: `paul`,
  pedro: `pedro`,
  pete: `pete`,
  rose: `rose`,
  sam: `sam`,
  sean: `sean`,
  sid: `sid`,
  slab: `slab`,
  suzy: `suzy`,
  uncle: `uncle`,
  vera: `vera`,
  willy: `willy`,
};

const SkillHealths = {
  [Skills.apache]: 3,
  [Skills.bart]: 4,
  [Skills.belle]: 4,
  [Skills.claus]: 3,
  [Skills.noface]: 4,
  [Skills.chuck]: 4,
  [Skills.duke]: 4,
  [Skills.elena]: 3,
  [Skills.greg]: 4,
  [Skills.gringo]: 3,
  [Skills.herb]: 4,
  [Skills.kit]: 4,
  [Skills.jack]: 4,
  [Skills.janet]: 4,
  [Skills.jesse]: 4,
  [Skills.joe]: 4,
  [Skills.johnny]: 4,
  [Skills.jose]: 4,
  [Skills.jourdonnais]: 4,
  [Skills.holyday]: 4,
  [Skills.molly]: 4,
  [Skills.pat]: 4,
  [Skills.paul]: 3,
  [Skills.pedro]: 4,
  [Skills.pete]: 3,
  [Skills.rose]: 4,
  [Skills.sam]: 4,
  [Skills.sean]: 3,
  [Skills.sid]: 4,
  [Skills.slab]: 4,
  [Skills.suzy]: 4,
  [Skills.vera]: 3,
  [Skills.willy]: 4,
  [Skills.uncle]: 4,
};

const Ranks = {
  ace: `A`,
  two: `2`,
  three: `3`,
  four: `4`,
  five: `5`,
  six: `6`,
  seven: `7`,
  eight: `8`,
  nine: `9`,
  ten: `10`,
  jack: `J`,
  queen: `Q`,
  king: `K`,
};

const Suits = {
  clubs: `clubs`,
  diamonds: `diamonds`,
  hearts: `hearts`,
  spades: `spades`,
};

const Expansions = {
  base: 'base',
  dodgecity: 'dodgecity',
  promo: 'promo',
};

const CardTitles = {
  [Actions.bang]: `Bang`,
  [Actions.beer]: `Beer`,
  [Actions.brawl]: `Brawl`,
  [Actions.catbalou]: `Cat Balou`,
  [Actions.dodge]: `Dodge`,
  [Actions.duel]: `Duel`,
  [Actions.gatling]: `Gatling`,
  [Actions.generalstore]: `General Store`,
  [Actions.indians]: `Indians`,
  [Actions.missed]: `Missed`,
  [Actions.panic]: `Panic`,
  [Actions.punch]: `Punch`,
  [Actions.ragtime]: `Rag Time`,
  [Actions.saloon]: `Saloon`,
  [Actions.springfield]: `Springfield`,
  [Actions.stagecoach]: `Stagecoach`,
  [Actions.tequila]: `Tequila`,
  [Actions.wellsfargo]: `Wells Fargo`,
  [Actions.whisky]: `Whisky`,
  [Items.barrel]: `Barrel`,
  [Items.binocular]: `Binocular`,
  [Items.dynamite]: `Dynamite`,
  [Items.hideout]: `Hideout`,
  [Items.jail]: `Jail`,
  [Items.mustang]: `Mustang`,
  [Items.remington]: `Remington`,
  [Items.revcarbine]: `Rev. Carbine`,
  [Items.schofield]: `Schofield`,
  [Items.scope]: `Scope`,
  [Items.volcanic]: `Volcanic`,
  [Items.winchester]: `Winchester`,
  [Roles.deputy]: `Deputy`,
  [Roles.outlaw]: `Outlaw`,
  [Roles.renegade]: `Renegade`,
  [Roles.sheriff]: `Sheriff`,
  [Skills.apache]: `Apache Kid`,
  [Skills.bart]: `Bart Cassidy`,
  [Skills.belle]: `Belle Star`,
  [Skills.chuck]: `Chuck Wengam`,
  [Skills.claus]: `Claus "The Saint"`,
  [Skills.duke]: `Lucky Duke`,
  [Skills.elena]: `Elena Fuente`,
  [Skills.greg]: `Greg Digger`,
  [Skills.gringo]: `El Gringo`,
  [Skills.herb]: `Herb Hunter`,
  [Skills.holyday]: `Doc Holyday`,
  [Skills.jack]: `Black Jack`,
  [Skills.janet]: `Calamity Janet`,
  [Skills.jesse]: `Jesse Jones`,
  [Skills.joe]: `Tequila Joe`,
  [Skills.johnny]: `Johnny Kisch`,
  [Skills.jose]: `Jose' Delgado`,
  [Skills.jourdonnais]: `Jourdonnais`,
  [Skills.kit]: `Kit Carlson`,
  [Skills.molly]: `Molly Stark`,
  [Skills.noface]: `Bill Noface`,
  [Skills.pat]: `Pat Brennan`,
  [Skills.paul]: `Paul Regret`,
  [Skills.pedro]: `Pedro Ramirez`,
  [Skills.pete]: `Pixie Pete`,
  [Skills.rose]: `Rose Doolan`,
  [Skills.sam]: `Vulture Sam`,
  [Skills.sean]: `Sean Mallory`,
  [Skills.sid]: `Sid Ketchum`,
  [Skills.slab]: `Slab the Killer`,
  [Skills.suzy]: `Suzy Lafayette`,
  [Skills.uncle]: `Uncle Will`,
  [Skills.vera]: `Vera Custer`,
  [Skills.willy]: `Willy the Kid`,
  [QueueableActions.bible]: `Bible`,
  [QueueableActions.buffalorifle]: `Buffalo Rifle`,
  [QueueableActions.cancan]: `Can Can`,
  [QueueableActions.canteen]: `Canteen`,
  [QueueableActions.conestoga]: `Conestoga`,
  [QueueableActions.derringer]: `Derringer`,
  [QueueableActions.howitzer]: `Howitzer`,
  [QueueableActions.ironplate]: `Iron Plate`,
  [QueueableActions.knife]: `Knife`,
  [QueueableActions.pepperbox]: `Pepperbox`,
  [QueueableActions.ponyexpress]: `Pony Express`,
  [QueueableActions.sombrero]: `Sombrero`,
  [QueueableActions.tengallonhat]: `Ten Gallon Hat`,
};

const CardInfos = {
  [Actions.bang]: `TARGET a player in your shooting range, and PLAY this card to shoot them. Only one can be played out of your hand per turn. Target will need a miss-type card.`,
  [Actions.beer]: `PLAY this card, during your turn, to regain a health point, up to the maximum of your skills. Will be played automatically, out of turn, if your health goes to zero.`,
  [Actions.brawl]: `ADD any one card from every other player as a TARGETS (to be discarded), SELECT another card from your hand (to be discarded), and PLAY this card.`,
  [Actions.catbalou]: `TARGET any card, in a hand or in play, to be discarded, and PLAY this card.`,
  [Actions.dodge]: `PLAY this card when you need to defend with a miss-type card. You will automatically draw another card.`,
  [Actions.duel]: `TARGET a player to duel, and PLAY this card. You will take turns PLAYING ${CardTitles[Actions.bang]} cards (target starts). First to run out loses a health point.`,
  [Actions.gatling]: `PLAY this card to shoot all other players. Others must defend themselves with a miss-type card.`,
  [Actions.generalstore]: `PLAY this card to automatically reveal enough cards from the deck as there are player. Everyone takes turn SELECTING one. You first.`,
  [Actions.indians]: `PLAY this card to attack all other players. Others must defend themselves with a ${CardTitles[Actions.bang]} card.`,
  [Actions.missed]: `PLAY this miss-type card out of turn to miss a shot.`,
  [Actions.panic]: `TARGET any card (to be stolen), in a hand or in play, from a player in your vision range, then PLAY this card to steal it.`,
  [Actions.punch]: `TARGET a player in your vision range, and PLAY this card to punch them. Target will need a miss-type card.`,
  [Actions.ragtime]: `TARGET any card (to be stolen), in a hand or in play, SELECT another card from your hand (to be discarded), and PLAY this card to steal the targeted card.`,
  [Actions.saloon]: `PLAY this card to allow everyone to gain a health point, up to the maximum of their skills.`,
  [Actions.springfield]: `TARGET any player (to be shot), SELECT another card from your hand (to be discarded), and PLAY this card to shoot them. Target will need a miss-type card.`,
  [Actions.stagecoach]: `PLAY this card to automatically draw 2 cards.`,
  [Actions.tequila]: `TARGET any player, SELECT another card from your hand (to be discarded), and PLAY this card to give them a health point, up to the maximum of their skills.`,
  [Actions.wellsfargo]: `PLAY this card to automatically draw 3 cards.`,
  [Actions.whisky]: `SELECT another card from your hand (to be discarded), and PLAY this card to give yourself 2 health points, up to the maximum of their skills.`,
  [Items.barrel]: `PLAY this card to equip it. When you are shot, DRAW a card and if it's hearts, the shot misses you.`,
  [Items.binocular]: `PLAY this card to equip it. Your vision and shooting range in increased by 1 (i.e. you can see further away).`,
  [Items.dynamite]: `PLAY this card to equip it. When starting your next turn, DRAW a card from the deck. If it's 2-9 of spades, you lose 3 health points. If not, pass it to the next player.`,
  [Items.hideout]: `PLAY this card to equip it. Others' vision and shooting range to you is decreased by 1 (i.e. you are further away).`,
  [Items.jail]: `TARGET a player and PLAY this card to put anyone, other than the Sheriff, in jail. At the start of their turn, they skip their turn if they don't DRAW a heart.`,
  [Items.mustang]: `PLAY this card to equip it. Others' vision and shooting range to you is decreased by 1 (i.e. you are further away).`,
  [Items.remington]: `PLAY this card to equip it. It sets your base shooting range to 3. This will replace any gun in your equipment.`,
  [Items.revcarbine]: `PLAY this card to equip it. It sets your base shooting range to 4. This will replace any gun in your equipment.`,
  [Items.schofield]: `PLAY this card to equip it. It sets your base shooting range to 2. This will replace any gun in your equipment.`,
  [Items.scope]: `PLAY this card to equip it. Your vision and shooting range in increased by 1 (i.e. you can see further away).`,
  [Items.volcanic]: `PLAY this card to equip it. It sets your base shooting range to 1, but removes your per-turn ${CardTitles[Actions.bang]} limit. This will replace any gun in your equipment.`,
  [Items.winchester]: `PLAY this card to equip it. It sets your base shooting range to 5. This will replace any gun in your equipment.`,
  [Roles.deputy]: `Protect the ${CardTitles[Roles.sheriff]}. If he dies, you lose. If he survives you win, regardless if you are still alive.`,
  [Roles.outlaw]: `Kill the ${CardTitles[Roles.sheriff]}. If he dies, you win. If he survives you lose, regardless if you are still alive.`,
  [Roles.renegade]: `Be the last one alive. Ideally, you want to help the ${CardTitles[Roles.sheriff]} enough to survive the ${CardTitles[Roles.outlaw]}s.`,
  [Roles.sheriff]: `Your max attainable health is increased by 1. Outside of one on one, you cannot be put in jail.`,
  [Skills.apache]: `Cards of suit diamonds do not affect you.`,
  [Skills.bart]: `When you lose a health point, you will automatically draw a card.`,
  [Skills.belle]: `Opponent equipment is disabled during your turn.`,
  [Skills.chuck]: `TARGET this skill and CLICK on your bullets (health points) to lose a health point and automatically draw 2 cards. Can only be done once per turn.`,
  [Skills.claus]: `At the start of your turn, you'll DRAW enough cards for all players and 2 for yourself. SELECT cards to be given to each other player, respectively, in order. Then PLAY.`,
  [Skills.duke]: `Any time you must DRAW a card, you will get 2 and you must DISCARD one. Jail and Barrel best outcomes are automatic.`,
  [Skills.elena]: `PLAY any card as a miss-type card.`,
  [Skills.greg]: `You gain 2 health points, up to the maximum of your skills, when anyone dies.`,
  [Skills.gringo]: `When you lose a health point, you will automatically get a card from the attacker's hand, if they have any.`,
  [Skills.herb]: `You automatically draw 2 cards when anyone dies.`,
  [Skills.holyday]: `TARGET a player in your shooting range, and from your hand, SELECT one card (to be discarded) and DISCARD another card, to shoot the target. Can be done once per turn.`,
  [Skills.jack]: `If the second card you DRAW is a heart or diamond, you wil be able to DRAW another card.`,
  [Skills.janet]: `You can play ${CardTitles[Actions.bang]} cards as ${CardTitles[Actions.missed]} cards, and vice versa.`,
  [Skills.jesse]: `At the start of your turn, you may DRAW your first card from any other player's hand.`,
  [Skills.johnny]: `WHEN you PLAY a card to be equipped, all other cards of the same name are discarded from other players' equipment`,
  [Skills.joe]: `When you PLAY a ${CardTitles[Actions.beer]}, or it is used in an emergency, it give you 2 health points.`,
  [Skills.jose]: `TARGET this skill, and DISCARD a blue item card, from your hand, to automatically draw 2 more cards. You can do this twice per turn.`,
  [Skills.jourdonnais]: `When you are shot, DRAW a card and if it's hearts, the shot misses you.`,
  [Skills.kit]: `At the start of your turn, you DRAW three cards and must DISCARD one to be returned to the top of the deck.`,
  [Skills.molly]: `Any time you PLAY a card out of turn, you will automatically pick a card up.`,
  [Skills.noface]: `At the start of your turn, you will DRAW an amount of card equal to one plus the amount of damage you have.`,
  [Skills.pat]: `At the start of your turn, you MAY draw any card from in play.`,
  [Skills.paul]: `Others' vision and shooting range to you is decreased by 1 (i.e. you are further away).`,
  [Skills.pedro]: `At the start of your turn, you may DRAW a card from the discard pile as your first card.`,
  [Skills.pete]: `At the start of your turn, you DRAW 3 cards.`,
  [Skills.rose]: `Your vision and shooting range in increased by 1 (i.e. you can see further away).`,
  [Skills.sam]: `When someone dies, you get their hand, if they have any cards.`,
  [Skills.sean]: `You can hold up to 10 cards when your turn is ended.`,
  [Skills.sid]: `From your hand, SELECT one card (to be discarded) and DISCARD another card to gain one health point. This can be done at any time.`,
  [Skills.slab]: `When you PLAY a ${CardTitles[Actions.bang]} against a target, they need 2 miss-type cards to evade.`,
  [Skills.suzy]: `Any time your hand is empty, you automatically draw a card.`,
  [Skills.uncle]: `TARGET this skill, and DISCARD any card, from your hand, to play a ${CardTitles[Actions.generalstore]}. You can do this once per turn.`,
  [Skills.vera]: `At the start of your turn, or when played, you must MIMIC another skill in play. The effects wil last for 1 turn.`,
  [Skills.willy]: `You can PLAY as many ${CardTitles[Actions.bang]}s in a turn as you wish.`,
  [QueueableActions.bible]: `PLAY this card to equip it. Once your turn is done, you can PLAY this card, from your equipment, as a miss-type card, and you will automatically draw a card.`,
  [QueueableActions.buffalorifle]: `PLAY this card to equip it. During any future turn, you can PLAY this card, from your equipment, to shoot any player.`,
  [QueueableActions.cancan]: `PLAY this card to equip it.  During any future turn, you can PLAY this card, from your equipment, to discard any card in play.`,
  [QueueableActions.canteen]: `PLAY this card to equip it. During any future turn, you can PLAY this card, from your equipment, to regain 1 health point.`,
  [QueueableActions.conestoga]: `PLAY this card to equip it. During any future turn, you can PLAY this card, from your equipment, to steal any card in play.`,
  [QueueableActions.derringer]: `PLAY this card to equip it. During any future turn, TARGET any player in your vision range and PLAY this card, from your equipment, to shoot that player and automatically draw a card.`,
  [QueueableActions.howitzer]: `PLAY this card to equip it. During any future turn, you can PLAY this card, from your equipment, to shoot every player.`,
  [QueueableActions.ironplate]: `PLAY this card to equip it. Once your turn is done, you can PLAY this card, from your equipment, as a miss-type card.`,
  [QueueableActions.knife]: `PLAY this card to equip it. During any future turn, TARGET any player in your vision range and PLAY this card, from your equipment, to shoot that player.`,
  [QueueableActions.pepperbox]: `PLAY this card to equip it. During any future turn, TARGET any player in your shooting range and PLAY this card, from your equipment, to shoot that player.`,
  [QueueableActions.ponyexpress]: `PLAY this card to equip it. During any future turn, PLAY this card, from your equipment, to automatically draw 3 cards.`,
  [QueueableActions.sombrero]: `PLAY this card to equip it. Once your turn is done, you can PLAY this card, from your equipment, as a miss-type card.`,
  [QueueableActions.tengallonhat]: `PLAY this card to equip it. Once your turn is done, you can PLAY this card, from your equipment, as a miss-type card.`,
};

const CardTypes = {
  action: `action`,
  item: `item`,
  queueableAction: `queueableAction`,
  role: `role`,
  skill: `skill`,
};

const Decks = {
  [Expansions.base]: [
    { name: Actions.bang, type: CardTypes.action, suit: Suits.clubs, rank: Ranks.two },
    { name: Actions.bang, type: CardTypes.action, suit: Suits.clubs, rank: Ranks.three },
    { name: Actions.bang, type: CardTypes.action, suit: Suits.clubs, rank: Ranks.four },
    { name: Actions.bang, type: CardTypes.action, suit: Suits.clubs, rank: Ranks.five },
    { name: Actions.bang, type: CardTypes.action, suit: Suits.clubs, rank: Ranks.six },
    { name: Actions.bang, type: CardTypes.action, suit: Suits.clubs, rank: Ranks.seven },
    { name: Actions.bang, type: CardTypes.action, suit: Suits.clubs, rank: Ranks.eight },
    { name: Actions.bang, type: CardTypes.action, suit: Suits.clubs, rank: Ranks.nine },
    { name: Actions.bang, type: CardTypes.action, suit: Suits.spades, rank: Ranks.ace },
    { name: Actions.bang, type: CardTypes.action, suit: Suits.hearts, rank: Ranks.queen },
    { name: Actions.bang, type: CardTypes.action, suit: Suits.hearts, rank: Ranks.king },
    { name: Actions.bang, type: CardTypes.action, suit: Suits.hearts, rank: Ranks.ace },
    { name: Actions.bang, type: CardTypes.action, suit: Suits.diamonds, rank: Ranks.two },
    { name: Actions.bang, type: CardTypes.action, suit: Suits.diamonds, rank: Ranks.three },
    { name: Actions.bang, type: CardTypes.action, suit: Suits.diamonds, rank: Ranks.four },
    { name: Actions.bang, type: CardTypes.action, suit: Suits.diamonds, rank: Ranks.five },
    { name: Actions.bang, type: CardTypes.action, suit: Suits.diamonds, rank: Ranks.six },
    { name: Actions.bang, type: CardTypes.action, suit: Suits.diamonds, rank: Ranks.seven },
    { name: Actions.bang, type: CardTypes.action, suit: Suits.diamonds, rank: Ranks.eight },
    { name: Actions.bang, type: CardTypes.action, suit: Suits.diamonds, rank: Ranks.nine },
    { name: Actions.bang, type: CardTypes.action, suit: Suits.diamonds, rank: Ranks.ten },
    { name: Actions.bang, type: CardTypes.action, suit: Suits.diamonds, rank: Ranks.jack },
    { name: Actions.bang, type: CardTypes.action, suit: Suits.diamonds, rank: Ranks.queen },
    { name: Actions.bang, type: CardTypes.action, suit: Suits.diamonds, rank: Ranks.king },
    { name: Actions.bang, type: CardTypes.action, suit: Suits.diamonds, rank: Ranks.ace },
    { name: Actions.beer, type: CardTypes.action, suit: Suits.hearts, rank: Ranks.six },
    { name: Actions.beer, type: CardTypes.action, suit: Suits.hearts, rank: Ranks.seven },
    { name: Actions.beer, type: CardTypes.action, suit: Suits.hearts, rank: Ranks.eight },
    { name: Actions.beer, type: CardTypes.action, suit: Suits.hearts, rank: Ranks.nine },
    { name: Actions.beer, type: CardTypes.action, suit: Suits.hearts, rank: Ranks.ten },
    { name: Actions.beer, type: CardTypes.action, suit: Suits.hearts, rank: Ranks.jack },
    { name: Actions.catbalou, type: CardTypes.action, suit: Suits.diamonds, rank: Ranks.nine },
    { name: Actions.catbalou, type: CardTypes.action, suit: Suits.diamonds, rank: Ranks.ten },
    { name: Actions.catbalou, type: CardTypes.action, suit: Suits.diamonds, rank: Ranks.jack },
    { name: Actions.catbalou, type: CardTypes.action, suit: Suits.hearts, rank: Ranks.king },
    { name: Actions.duel, type: CardTypes.action, suit: Suits.diamonds, rank: Ranks.queen },
    { name: Actions.duel, type: CardTypes.action, suit: Suits.spades, rank: Ranks.jack },
    { name: Actions.duel, type: CardTypes.action, suit: Suits.clubs, rank: Ranks.eight },
    { name: Actions.gatling, type: CardTypes.action, suit: Suits.hearts, rank: Ranks.ten },
    { name: Actions.generalstore, type: CardTypes.action, suit: Suits.spades, rank: Ranks.queen },
    { name: Actions.generalstore, type: CardTypes.action, suit: Suits.clubs, rank: Ranks.nine },
    { name: Actions.indians, type: CardTypes.action, suit: Suits.diamonds, rank: Ranks.queen },
    { name: Actions.indians, type: CardTypes.action, suit: Suits.diamonds, rank: Ranks.ace },
    { name: Actions.missed, type: CardTypes.action, suit: Suits.clubs, rank: Ranks.ten },
    { name: Actions.missed, type: CardTypes.action, suit: Suits.clubs, rank: Ranks.jack },
    { name: Actions.missed, type: CardTypes.action, suit: Suits.clubs, rank: Ranks.queen },
    { name: Actions.missed, type: CardTypes.action, suit: Suits.clubs, rank: Ranks.king },
    { name: Actions.missed, type: CardTypes.action, suit: Suits.clubs, rank: Ranks.ace },
    { name: Actions.missed, type: CardTypes.action, suit: Suits.spades, rank: Ranks.two },
    { name: Actions.missed, type: CardTypes.action, suit: Suits.spades, rank: Ranks.three },
    { name: Actions.missed, type: CardTypes.action, suit: Suits.spades, rank: Ranks.four },
    { name: Actions.missed, type: CardTypes.action, suit: Suits.spades, rank: Ranks.five },
    { name: Actions.missed, type: CardTypes.action, suit: Suits.spades, rank: Ranks.six },
    { name: Actions.missed, type: CardTypes.action, suit: Suits.spades, rank: Ranks.seven },
    { name: Actions.missed, type: CardTypes.action, suit: Suits.spades, rank: Ranks.eight },
    { name: Actions.panic, type: CardTypes.action, suit: Suits.diamonds, rank: Ranks.eight },
    { name: Actions.panic, type: CardTypes.action, suit: Suits.hearts, rank: Ranks.jack },
    { name: Actions.panic, type: CardTypes.action, suit: Suits.hearts, rank: Ranks.queen },
    { name: Actions.panic, type: CardTypes.action, suit: Suits.hearts, rank: Ranks.ace },
    { name: Actions.saloon, type: CardTypes.action, suit: Suits.hearts, rank: Ranks.five },
    { name: Actions.stagecoach, type: CardTypes.action, suit: Suits.spades, rank: Ranks.nine },
    { name: Actions.stagecoach, type: CardTypes.action, suit: Suits.spades, rank: Ranks.nine },
    { name: Actions.wellsfargo, type: CardTypes.action, suit: Suits.hearts, rank: Ranks.three },
    { name: Items.barrel, type: CardTypes.item, suit: Suits.spades, rank: Ranks.queen },
    { name: Items.barrel, type: CardTypes.item, suit: Suits.spades, rank: Ranks.king },
    { name: Items.dynamite, type: CardTypes.item, suit: Suits.hearts, rank: Ranks.two },
    { name: Items.jail, type: CardTypes.item, suit: Suits.hearts, rank: Ranks.four },
    { name: Items.jail, type: CardTypes.item, suit: Suits.spades, rank: Ranks.ten },
    { name: Items.jail, type: CardTypes.item, suit: Suits.spades, rank: Ranks.jack },
    { name: Items.mustang, type: CardTypes.item, suit: Suits.hearts, rank: Ranks.eight },
    { name: Items.mustang, type: CardTypes.item, suit: Suits.hearts, rank: Ranks.nine },
    { name: Items.schofield, type: CardTypes.item, suit: Suits.spades, rank: Ranks.king },
    { name: Items.schofield, type: CardTypes.item, suit: Suits.clubs, rank: Ranks.jack },
    { name: Items.schofield, type: CardTypes.item, suit: Suits.clubs, rank: Ranks.queen },
    { name: Items.scope, type: CardTypes.item, suit: Suits.spades, rank: Ranks.ace },
    { name: Items.remington, type: CardTypes.item, suit: Suits.clubs, rank: Ranks.king },
    { name: Items.revcarbine, type: CardTypes.item, suit: Suits.clubs, rank: Ranks.ace },
    { name: Items.volcanic, type: CardTypes.item, suit: Suits.clubs, rank: Ranks.ten },
    { name: Items.volcanic, type: CardTypes.item, suit: Suits.spades, rank: Ranks.ten },
    { name: Items.winchester, type: CardTypes.item, suit: Suits.spades, rank: Ranks.eight },
    { name: Skills.bart, type: CardTypes.skill },
    { name: Skills.duke, type: CardTypes.skill },
    { name: Skills.gringo, type: CardTypes.skill },
    { name: Skills.jack, type: CardTypes.skill },
    { name: Skills.janet, type: CardTypes.skill },
    { name: Skills.jesse, type: CardTypes.skill },
    { name: Skills.jourdonnais, type: CardTypes.skill },
    { name: Skills.kit, type: CardTypes.skill },
    { name: Skills.paul, type: CardTypes.skill },
    { name: Skills.pedro, type: CardTypes.skill },
    { name: Skills.rose, type: CardTypes.skill },
    { name: Skills.sam, type: CardTypes.skill },
    { name: Skills.sid, type: CardTypes.skill },
    { name: Skills.slab, type: CardTypes.skill },
    { name: Skills.suzy, type: CardTypes.skill },
    { name: Skills.willy, type: CardTypes.skill },
  ],
  [Expansions.dodgecity]: [
    { name: Actions.bang, type: CardTypes.action, suit: Suits.spades, rank: Ranks.eight },
    { name: Actions.bang, type: CardTypes.action, suit: Suits.clubs, rank: Ranks.five },
    { name: Actions.bang, type: CardTypes.action, suit: Suits.clubs, rank: Ranks.six },
    { name: Actions.bang, type: CardTypes.action, suit: Suits.clubs, rank: Ranks.king },
    { name: Actions.beer, type: CardTypes.action, suit: Suits.spades, rank: Ranks.six },
    { name: Actions.beer, type: CardTypes.action, suit: Suits.hearts, rank: Ranks.six },
    { name: Actions.brawl, type: CardTypes.action, suit: Suits.spades, rank: Ranks.jack },
    { name: Actions.catbalou, type: CardTypes.action, suit: Suits.clubs, rank: Ranks.eight },
    { name: Actions.dodge, type: CardTypes.action, suit: Suits.diamonds, rank: Ranks.seven },
    { name: Actions.dodge, type: CardTypes.action, suit: Suits.hearts, rank: Ranks.king },
    { name: Actions.generalstore, type: CardTypes.action, suit: Suits.spades, rank: Ranks.ace },
    { name: Actions.indians, type: CardTypes.action, suit: Suits.diamonds, rank: Ranks.five },
    { name: Actions.missed, type: CardTypes.action, suit: Suits.diamonds, rank: Ranks.eight },
    { name: Actions.panic, type: CardTypes.action, suit: Suits.hearts, rank: Ranks.jack },
    { name: Actions.punch, type: CardTypes.action, suit: Suits.spades, rank: Ranks.ten },
    { name: Actions.ragtime, type: CardTypes.action, suit: Suits.hearts, rank: Ranks.nine },
    { name: Actions.springfield, type: CardTypes.action, suit: Suits.spades, rank: Ranks.king },
    { name: Actions.tequila, type: CardTypes.action, suit: Suits.clubs, rank: Ranks.nine },
    { name: Actions.whisky, type: CardTypes.action, suit: Suits.hearts, rank: Ranks.queen },    // website says diamonds
    { name: Items.barrel, type: CardTypes.item, suit: Suits.clubs, rank: Ranks.ace },
    { name: Items.binocular, type: CardTypes.item, suit: Suits.diamonds, rank: Ranks.ten },
    { name: Items.dynamite, type: CardTypes.item, suit: Suits.clubs, rank: Ranks.ten },
    { name: Items.hideout, type: CardTypes.item, suit: Suits.diamonds, rank: Ranks.king },
    { name: Items.mustang, type: CardTypes.item, suit: Suits.hearts, rank: Ranks.five },
    { name: Items.remington, type: CardTypes.item, suit: Suits.diamonds, rank: Ranks.six },
    { name: Items.revcarbine, type: CardTypes.item, suit: Suits.spades, rank: Ranks.five },
    { name: Skills.apache, type: CardTypes.skill },
    { name: Skills.belle, type: CardTypes.skill },
    { name: Skills.chuck, type: CardTypes.skill },
    { name: Skills.elena, type: CardTypes.skill },
    { name: Skills.greg, type: CardTypes.skill },
    { name: Skills.herb, type: CardTypes.skill },
    { name: Skills.holyday, type: CardTypes.skill },
    { name: Skills.joe, type: CardTypes.skill },
    { name: Skills.jose, type: CardTypes.skill },
    { name: Skills.molly, type: CardTypes.skill },
    { name: Skills.noface, type: CardTypes.skill },
    { name: Skills.pat, type: CardTypes.skill },
    { name: Skills.pete, type: CardTypes.skill },
    { name: Skills.sean, type: CardTypes.skill },
    { name: Skills.vera, type: CardTypes.skill },
    { name: QueueableActions.bible, type: CardTypes.queueableAction, suit: Suits.hearts, rank: Ranks.ten },
    { name: QueueableActions.buffalorifle, type: CardTypes.queueableAction, suit: Suits.clubs, rank: Ranks.queen },
    { name: QueueableActions.cancan, type: CardTypes.queueableAction, suit: Suits.clubs, rank: Ranks.jack },
    { name: QueueableActions.canteen, type: CardTypes.queueableAction, suit: Suits.hearts, rank: Ranks.seven },
    { name: QueueableActions.conestoga, type: CardTypes.queueableAction, suit: Suits.diamonds, rank: Ranks.nine },
    { name: QueueableActions.derringer, type: CardTypes.queueableAction, suit: Suits.spades, rank: Ranks.seven },
    { name: QueueableActions.howitzer, type: CardTypes.queueableAction, suit: Suits.spades, rank: Ranks.nine },
    { name: QueueableActions.ironplate, type: CardTypes.queueableAction, suit: Suits.spades, rank: Ranks.queen },
    { name: QueueableActions.ironplate, type: CardTypes.queueableAction, suit: Suits.diamonds, rank: Ranks.ace },
    { name: QueueableActions.knife, type: CardTypes.queueableAction, suit: Suits.hearts, rank: Ranks.eight },
    { name: QueueableActions.pepperbox, type: CardTypes.queueableAction, suit: Suits.hearts, rank: Ranks.ace },
    { name: QueueableActions.ponyexpress, type: CardTypes.queueableAction, suit: Suits.diamonds, rank: Ranks.queen },
    { name: QueueableActions.sombrero, type: CardTypes.queueableAction, suit: Suits.clubs, rank: Ranks.seven },
    { name: QueueableActions.tengallonhat, type: CardTypes.queueableAction, suit: Suits.diamonds, rank: Ranks.jack },
  ],
  [Expansions.promo]: [
    { name: Skills.claus, type: CardTypes.skill },
    { name: Skills.johnny, type: CardTypes.skill },
    { name: Skills.uncle, type: CardTypes.skill },
  ],
};

module.exports = {
  Actions,
  CardInfos,
  CardTitles,
  CardTypes,
  Decks,
  Expansions,
  GunDistances,
  Items,
  QueueableActions,
  Ranks,
  Roles,
  SkillHealths,
  Skills,
  Suits,
};
